myBlog_Project/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'blog'

urlpatterns = [
    path('about',views.About_us.as_view(),name='about_us'),
    path('<slug:slug>', views.PostDetail.as_view(),name='post_detail'),
    path('new/',views.CreatePostView.as_view(),name='new_post'),
]

myBlog_Project/myBlog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('basic_app.urls')),
    path('draft',views.DraftListView.as_view(), name='draft'),
    path('logout', views.logout_request, name='logout'),
    path('', views.PostList.as_view(), name='home'),
    path("login", views.login_request, name="login"),
]

myBlog_Project/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

STATUS = (
    (0,"Draft"),
    (1,"Publish"),
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})


class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

myBlog_Project/basic_app/forms.py
from django import forms
from basic_app.models import Post, Comment
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class PostForm(forms.ModelForm):

    class Meta():
        model = Post
        fields = ('title','slug','content','author','status')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

myBlog_Project/basic_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from basic_app.models import Post, Comment
from django.contrib.auth import authenticate, login, logout
from basic_app.forms import PostForm, NewUserForm
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages

class About_us(TemplateView):
    template_name = "basic_app/about_us.html"


class PostList(ListView):
    queryset = Post.objects.all().filter(status=1).order_by('-created_on')
    template_name = "basic_app/post_list.html"


class PostDetail(DetailView):
    model = Post
    template_name = 'basic_app/post_detail.html'


class DraftListView(ListView):
    queryset = Post.objects.all().filter(status=0).order_by('-created_on')
    template_name = "basic_app/post_draft_list.html"


class CreatePostView(CreateView):
    form_class = PostForm
    model = Post


# def user_login(request):
    
#     username = request.POST('username')
#     password = request.POST('password')
#     user = authenticate(request, username=username, password=password)
#     if user is not None:
#         login(request, user)
#         return redirect('home')
#     else:
#         return HttpResponse("Either Username or Password Is Incorrect.")


def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}")
                return redirect('/')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request = request,
                    template_name = "basic_app/login.html",
                    context={"form":form})


def logout_request(request):
    logout(request)
    return redirect("home")

myBlog_Project/basic_app/templates/basic_app/about_us.html
{% extends 'basic_app/base.html' %}

{% block body_block %}
    <div class="rainbow">
        <h1>Thanks For Visiting Us.</h1>
    </div>
{% endblock body_block %}

myBlog_Project/basic_app/templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The Blog</title>
    <!-- CSS And JS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <!-- FONTS -->
    <link href="https://fonts.googleapis.com/css2?family=Metal+Mania&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital@1&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">

</head>
<body>
  <style>
    .card-title{
      color: brown;
      text-shadow: 2px 2px 4px #000000;
      font-family: 'Permanent Marker', cursive;
    }

    .card-text{
      font-family: 'Merriweather', serif;
    }

    .card-body{
      background-color: rgba(245, 245, 245, 0.671);
    }

    .title{
      font-family: 'Metal Mania', cursive;
    }

    .left{
      margin-left: 160px;
      position: static;
    }

    #dropdownMenuButton{
      color: black;
      border-style: hidden;
    }

    .blod_left{
      color: black;
    }

    .dropdown-menu{
      color: black;
    }

    .detail_title{
      color: brown;
      font-family: 'Permanent Marker', cursive;
    }

    .detail_text{
      font-family: 'Merriweather', serif;
    }

    .comment_section{
      font-family: 'Pacifico', cursive;
      font-size:40px;
      margin-top: 20px;
    }

    .rainbow{
      margin-top: 20px;
      font-family: 'Pacifico', cursive;
      text-shadow: 2px 2px 4px #000000;
      font-size:40px;
    }

    .foot{
      font-family: 'Pacifico', cursive;
      font-size: 20px; 
    }

    body{
      background-color: beige;
    }
  </style>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home' %}"> <b class="blod_left title">The Blog</b> </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="https://www.github.com"><b class="blod_left">GitHub</b></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://www.linkedin.com"><b class="blod_left">LinkedIn</b></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:about_us' %}"><b class="blod_left">About Us</b></a>
        </li>
      </ul>
    </div>

    <div class="dropdown">
      {% if user.is_authenticated %}
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <a><b class="bold_left">Welcome: {{user.username}}</b></a>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="nav-link" href="{% url 'blog:new_post' %}"> <b class="bold_right">New Post</b> </a>
          <a class="nav-link" href="{% url 'draft' %}"><b class="bold_right">Drafts</b></a>
          <a class="nav-link" href="{% url 'logout' %}"> <b class="bold_right">Log Out</b> </a>
        </div>
      {% else %}
        <button type="button" class="btn"><a class="nav navbar-nav navbar-right" href="{% url 'login' %}"> <b class="bold_right">Log In</b> </a></button>
      {% endif %}
    </div>
  </nav>

    <div class="container">
        {% block body_block %}

        {% endblock body_block %}
    </div>
    <footer class="py-3 bg-grey foot">
        <p class="m-0 text-dark text-center ">Copyright &copy; Prakhar</p>
    </footer>
</body>
</html>

myBlog_Project/basic_app/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}

{% block body_block %}
    <h1>Welcome</h1>
{% endblock body_block %}

myBlog_Project/basic_app/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <div class="container">
        <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
            <button class="btn btn-outline-info" type="submit">Login</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

myBlog_Project/basic_app/templates/basic_app/post_detail.html
{% extends 'basic_app/base.html' %}

{% block body_block %}
    <div class="row">
        <div class="col-md-8 card mb-4 mt-3 left top">
            <div class="card-body">
                <h1 class="detail_title">{{ post.title }}</h1>
                <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
                <p class="detail_text">{{ post.content | safe }}</p>
            </div>
        </div>
    </div>

    <div class="comment_section">
        <div class="container">
            <h2 class="comment-heading">Comments Section</h2>
            {% for comment in post.comments.all %}
                <div>
                    <p>{{ comment.body|safe|linebreaks }}</p>
                    <p><b>Posted By : </b>{{ comment.name }}</p>
                    <br>
                </div>
            {% endfor %}
        </div>
    </div>
        
{% endblock body_block %}

myBlog_Project/basic_app/templates/basic_app/post_draft_list.html
{% extends 'basic_app/base.html' %}

{% block body_block %}
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content}}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock body_block %}

myBlog_Project/basic_app/templates/basic_app/post_form.html
{% extends 'basic_app/base.html' %}

{% block body_block %}
    <div class="jumbotron">
        <h1>Fill Details For New Post.</h1>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Save</button>
        </form>
    </div>
{% endblock body_block %}

myBlog_Project/basic_app/templates/basic_app/post_list.html
{% extends 'basic_app/base.html' %}

{% block body_block %}
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'blog:post_detail' post.slug %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock body_block %}